In [3]:
from xgboost import XGBRegressor
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import explained_variance_score

In [4]:
new_df = pd.read_csv("Crypto data.csv")
new_df["Date"] = pd.to_datetime(new_df["Date"])
new_df.head(20)

Date         Open         High          Low        Close      Volume  \
0  2019-01-01  3746.713379  3850.913818  3707.231201  3843.520020  4324200990   
1  2019-01-02  3849.216309  3947.981201  3817.409424  3943.409424  5244856836   
2  2019-01-03  3931.048584  3935.685059  3826.222900  3836.741211  4530215219   
3  2019-01-04  3832.040039  3865.934570  3783.853760  3857.717529  4847965467   
4  2019-01-05  3851.973877  3904.903076  3836.900146  3845.194580  5137609824   
5  2019-01-06  3836.519043  4093.297363  3826.513184  4076.632568  5597027440   
6  2019-01-07  4078.584961  4092.613525  4020.894043  4025.248291  5228625637   
7  2019-01-08  4028.472168  4109.020996  3996.955322  4030.847900  5306593305   
8  2019-01-09  4031.552002  4068.403564  4022.662842  4035.296387  5115905225   
9  2019-01-10  4034.411377  4064.066650  3659.174561  3678.924561  6874143796   
10 2019-01-11  3674.015381  3713.881836  3653.069824  3687.365479  5538712865   
11 2019-01-12  3686.973145  3698.978271  3653.810791  3661.301025  4778170883   
12 2019-01-13  3658.868164  3674.760010  3544.927246  3552.953125  4681302466   
13 2019-01-14  3557.311035  3727.836182  3552.285156  3706.052246  5651384490   
14 2019-01-15  3704.216309  3720.153320  3619.949219  3630.675293  5537192302   
15 2019-01-16  3631.509766  3685.777100  3624.673340  3655.006836  5394457145   
16 2019-01-17  3651.871094  3680.135986  3621.960938  3678.563965  5464420383   
17 2019-01-18  3677.990479  3682.520020  3637.080811  3657.839355  5002961727   
18 2019-01-19  3652.377930  3758.533447  3652.377930  3728.568359  5955691380   
19 2019-01-20  3725.446045  3743.387939  3583.019531  3601.013672  5582489560   

    Dividends  Stock Splits     name symbols  
0           0             0  Bitcoin     BTC  
1           0             0  Bitcoin     BTC  
2           0             0  Bitcoin     BTC  
3           0             0  Bitcoin     BTC  
4           0             0  Bitcoin     BTC  
5           0             0  Bitcoin     BTC  
6           0             0  Bitcoin     BTC  
7           0             0  Bitcoin     BTC  
8           0             0  Bitcoin     BTC  
9           0             0  Bitcoin     BTC  
10          0             0  Bitcoin     BTC  
11          0             0  Bitcoin     BTC  
12          0             0  Bitcoin     BTC  
13          0             0  Bitcoin     BTC  
14          0             0  Bitcoin     BTC  
15          0             0  Bitcoin     BTC  
16          0             0  Bitcoin     BTC  
17          0             0  Bitcoin     BTC  
18          0             0  Bitcoin     BTC  
19          0             0  Bitcoin     BTC

In [5]:
Ada = new_df[new_df["symbols"]== "ADA"].copy()
new_ada = pd.DataFrame(Ada)
new_ada

Date      Open      High       Low     Close      Volume  \
10427 2019-01-01  0.040984  0.042547  0.040308  0.042547    14962902   
10428 2019-01-02  0.042568  0.045563  0.041982  0.045258    24151526   
10429 2019-01-03  0.045106  0.045259  0.042535  0.042682    21126963   
10430 2019-01-04  0.042629  0.044092  0.042477  0.043812    16024029   
10431 2019-01-05  0.043659  0.045570  0.043350  0.044701    25100965   
...          ...       ...       ...       ...       ...         ...   
11629 2022-04-17  0.952531  0.961512  0.915346  0.917466   528371933   
11630 2022-04-18  0.917509  0.937368  0.877736  0.936730  1105222191   
11631 2022-04-19  0.936762  0.954662  0.928201  0.953333   777142382   
11632 2022-04-20  0.953325  0.974735  0.932510  0.937341   828312845   
11633 2022-04-21  0.937272  0.969453  0.896912  0.910474   871111347   

       Dividends  Stock Splits    name symbols  
10427          0             0  Cadano     ADA  
10428          0             0  Cadano     ADA  
10429          0             0  Cadano     ADA  
10430          0             0  Cadano     ADA  
10431          0             0  Cadano     ADA  
...          ...           ...     ...     ...  
11629          0             0  Cadano     ADA  
11630          0             0  Cadano     ADA  
11631          0             0  Cadano     ADA  
11632          0             0  Cadano     ADA  
11633          0             0  Cadano     ADA  

[1207 rows x 10 columns]

In [6]:
new_ada. describe()

Open         High          Low        Close        Volume  \
count  1207.000000  1207.000000  1207.000000  1207.000000  1.207000e+03   
mean      0.592888     0.618253     0.566352     0.593653  1.569623e+09   
std       0.742570     0.773773     0.709357     0.742601  2.428508e+09   
min       0.023954     0.025993     0.019130     0.023961  1.101152e+07   
25%       0.049988     0.051733     0.048424     0.050127  8.828525e+07   
50%       0.103097     0.106979     0.100179     0.104008  4.778389e+08   
75%       1.185676     1.225057     1.142402     1.185525  2.095375e+09   
max       2.966390     3.099186     2.907606     2.968239  1.914198e+10   

       Dividends  Stock Splits  
count     1207.0        1207.0  
mean         0.0           0.0  
std          0.0           0.0  
min          0.0           0.0  
25%          0.0           0.0  
50%          0.0           0.0  
75%          0.0           0.0  
max          0.0           0.0

In [7]:
#Dropping the dropping the unnecessary data
new_ada.drop(['name', 'Date', "Dividends" , "Stock Splits", "symbols" ], axis = 1, inplace = True)

new_ada.head()

Open      High       Low     Close    Volume
10427  0.040984  0.042547  0.040308  0.042547  14962902
10428  0.042568  0.045563  0.041982  0.045258  24151526
10429  0.045106  0.045259  0.042535  0.042682  21126963
10430  0.042629  0.044092  0.042477  0.043812  16024029
10431  0.043659  0.045570  0.043350  0.044701  25100965

In [8]:
#extracting the independent and dependent variable
x =  np.array(new_ada.drop(['Close'], 1))
#print(x)
y = np.array(new_ada['Close'])

C:\Users\nudou\AppData\Local\Temp\ipykernel_20024\545680320.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x =  np.array(new_ada.drop(['Close'], 1))


In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)# 70% training and 30% test
print(y_test)

[0.138303   0.049261   0.077955   0.028249   0.046163   0.049664
 0.036048   1.39439702 0.044172   0.039532   0.036559   0.083472
 1.68642294 1.05026698 1.06671596 1.46554101 0.085442   0.0795
 0.059466   0.29998001 1.35424805 2.10856009 0.033215   1.36203003
 0.105866   2.91738605 0.133505   0.058772   0.122688   1.18913996
 0.125214   0.123773   0.083445   0.034462   0.04281    0.043873
 1.05165696 0.031984   0.0406     0.106104   1.34175706 0.110572
 1.40311801 0.108083   2.33094096 1.24053395 0.95982802 1.41178596
 0.041967   0.04575    0.045879   2.30154109 1.16852295 0.082817
 0.038229   0.066146   0.044043   0.046601   0.137398   0.104525
 2.502491   0.041058   1.37697506 0.053793   1.75050294 0.041495
 1.59413099 0.12927499 0.08387    0.092143   0.106621   0.05864
 1.37758398 2.36997795 0.08069    0.050932   1.31772995 0.052169
 0.044328   0.042297   0.04941    0.049767   0.036198   0.044437
 1.98620605 1.76407695 0.153964   1.48252106 0.096348   0.096578
 2.10180211 0.047677  

In [10]:
scaler = MinMaxScaler()
scaled_x_train = scaler.fit_transform(x_train)
scaled_x_test = scaler.fit_transform(x_test)
scaled_y_train = scaler.fit_transform(np.array(y_train).reshape(-1, 1))
scaled_y_test = scaler.fit_transform(np.array(y_test).reshape(-1, 1))

In [11]:

# Training the model
xgb_model = XGBRegressor(n_estimators=10000, max_depth=7, eta=0.1, subsample=0.7, colsample_bytree=0.8)

xgb_model.fit(scaled_x_train, scaled_y_train)
xgb_prediction = xgb_model.predict(scaled_x_test)

#checking for model accuracy
rmse = np.sqrt(mean_squared_error(scaled_y_test, xgb_prediction))
mae = mean_absolute_error(scaled_y_test, xgb_prediction)

print('Root Mean Square Error:', rmse)
print('Mean Absolute Error:', mae)





Root Mean Square Error: 0.015298230269857487
Mean Absolute Error: 0.007542214898754753


In [12]:
#checking for accuracy score

print(xgb_prediction[:10])
print(scaled_x_test[:10])

from sklearn.metrics import r2_score

rfr_prediction = xgb_model.predict(scaled_x_test)


print(rfr_prediction[:10])
print(scaled_x_test[:10])

print('Test R^2     : %.3f'%r2_score(scaled_y_test, xgb_prediction))
print('Test R^2     : %.3f'%xgb_model.score(scaled_x_test, scaled_y_test))
print('Training R^2 : %.3f'%xgb_model.score(scaled_x_train, scaled_y_train))



[0.0406671  0.00722635 0.01904053 0.00091289 0.00717844 0.00787008
 0.00321725 0.47854513 0.00626721 0.00477231]
[[3.84454413e-02 3.89742336e-02 4.12893056e-02 2.03772608e-02]
 [6.62999017e-03 8.03833572e-03 8.06639654e-03 2.45742488e-03]
 [2.01939284e-02 2.02172093e-02 1.98924958e-02 7.33336482e-03]
 [1.53985746e-03 1.31093802e-03 2.15388406e-03 3.66344079e-03]
 [6.74286927e-03 6.85726717e-03 8.11266627e-03 3.91767091e-04]
 [8.07668816e-03 8.23925966e-03 8.71704556e-03 9.87207465e-03]
 [3.51355408e-03 3.80464423e-03 3.98710692e-03 5.23784785e-03]
 [4.44628554e-01 4.65221230e-01 4.53512699e-01 1.31765488e-01]
 [6.38144968e-03 6.34458657e-03 7.63669523e-03 3.09626834e-03]
 [4.42713262e-03 4.73617169e-03 5.37628243e-03 4.25491768e-03]]
[0.0406671  0.00722635 0.01904053 0.00091289 0.00717844 0.00787008
 0.00321725 0.47854513 0.00626721 0.00477231]
[[3.84454413e-02 3.89742336e-02 4.12893056e-02 2.03772608e-02]
 [6.62999017e-03 8.03833572e-03 8.06639654e-03 2.45742488e-03]
 [2.01939284e-02 